/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/waldow.glb 
*/

import { useAnimations, useFBX, useGLTF } from '@react-three/drei';
import { button, folder, useControls } from 'leva';
import { Suspense, useEffect, useRef } from 'react';
import type { JSX } from 'react/jsx-runtime';
import type { Group, MeshStandardMaterial, SkinnedMesh } from 'three';
import type { GLTF } from 'three-stdlib';

type NodeMeshes = {
  Hips: Group;
  Wolf3D_Hair: SkinnedMesh;
  Wolf3D_Outfit_Top: SkinnedMesh;
  Wolf3D_Outfit_Bottom: SkinnedMesh;
  Wolf3D_Outfit_Footwear: SkinnedMesh;
  Wolf3D_Body: SkinnedMesh;
  EyeLeft: SkinnedMesh;
  EyeRight: SkinnedMesh;
  Wolf3D_Head: SkinnedMesh;
  Wolf3D_Teeth: SkinnedMesh;
};

type GLTFResult = GLTF & {
  nodes: NodeMeshes;
  meshes: NodeMeshes;
  materials: {
    Wolf3D_Hair: MeshStandardMaterial;
    Wolf3D_Outfit_Top: MeshStandardMaterial;
    Wolf3D_Outfit_Bottom: MeshStandardMaterial;
    Wolf3D_Outfit_Footwear: MeshStandardMaterial;
    Wolf3D_Body: MeshStandardMaterial;
    Wolf3D_Eye: MeshStandardMaterial;
    Wolf3D_Skin: MeshStandardMaterial;
    Wolf3D_Teeth: MeshStandardMaterial;
  };
};

const ANIMATION = {
  TYPING: 'TYPING',
};

export const WaldowAvatar = (props: JSX.IntrinsicElements['group']) => {
  // @ts-expect-error ...
  const group = useRef<Group>();
  // @ts-ignore
  const { nodes, materials } = useGLTF('/models/waldow.glb') as GLTFResult;
  const { animations: typingAnimation } = useFBX('/animations/typing.fbx');
  const { actions } = useAnimations(typingAnimation, group);

  typingAnimation[0].name = ANIMATION.TYPING;
  materials.Wolf3D_Outfit_Top.color.set('cyan');

  useEffect(() => {
    console.log({ typingAnimation, actions });
    actions?.[ANIMATION.TYPING]?.reset().play();
  }, [actions]);

  const defaultValues = {
    position: { x: 0.73, y: -4.84, z: 4.85 },
    rotation: { x: -Math.PI / 2, y: 0, z: Math.PI },
    scale: 7.8,
  };

  const [{ position, rotation, scale }, set] = useControls(
    'Coding Scene',
    () => ({
      waldowAvatar: folder(
        {
          position: {
            x: defaultValues.position.x,
            y: defaultValues.position.y,
            z: defaultValues.position.z,
          },
          rotation: {
            x: defaultValues.rotation.x,
            y: defaultValues.rotation.y,
            z: defaultValues.rotation.z,
          },
          scale: {
            value: defaultValues.scale,
            min: 0.1,
            max: 10,
            step: 0.1,
          },
          'Reset Defaults': button(() => set(defaultValues)),
        },
        { collapsed: true },
      ),
    }),
  );

  return (
    <Suspense fallback={'Loading...'}>
      <group ref={group} {...props} dispose={null}>
        <group
          scale={scale}
          rotation={[rotation.x, rotation.y, rotation.z]}
          position={[position.x, position.y, position.z]}
        >
          <primitive object={nodes.Hips} />
          <skinnedMesh
            geometry={nodes.Wolf3D_Hair.geometry}
            material={materials.Wolf3D_Hair}
            skeleton={nodes.Wolf3D_Hair.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Wolf3D_Outfit_Top.geometry}
            material={materials.Wolf3D_Outfit_Top}
            skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
            material={materials.Wolf3D_Outfit_Bottom}
            skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
            material={materials.Wolf3D_Outfit_Footwear}
            skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Wolf3D_Body.geometry}
            material={materials.Wolf3D_Body}
            skeleton={nodes.Wolf3D_Body.skeleton}
          />
          <skinnedMesh
            name={'EyeLeft'}
            geometry={nodes.EyeLeft.geometry}
            material={materials.Wolf3D_Eye}
            skeleton={nodes.EyeLeft.skeleton}
            morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
            morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
          />
          <skinnedMesh
            name={'EyeRight'}
            geometry={nodes.EyeRight.geometry}
            material={materials.Wolf3D_Eye}
            skeleton={nodes.EyeRight.skeleton}
            morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
            morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
          />
          <skinnedMesh
            name={'Wolf3D_Head'}
            geometry={nodes.Wolf3D_Head.geometry}
            material={materials.Wolf3D_Skin}
            skeleton={nodes.Wolf3D_Head.skeleton}
            morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
            morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
          />
          <skinnedMesh
            name={'Wolf3D_Teeth'}
            geometry={nodes.Wolf3D_Teeth.geometry}
            material={materials.Wolf3D_Teeth}
            skeleton={nodes.Wolf3D_Teeth.skeleton}
            morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
            morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
          />
        </group>
      </group>
    </Suspense>
  );
};

useGLTF.preload('/models/waldow.glb');
