name: Create diagram
on:
  workflow_dispatch: {}
  push:
    branches:
      - dev
jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Update diagram
        uses: githubocto/repo-visualizer@0.9.1
        with:
          excluded_paths: "ignore,.github,.idea,node_modules,dist,out,build,eject,.netlify,pnpm-lock.yaml,.pnp.loader.mjs,.pnp.cjs,src/output.css"

